version: '4.0'

services:
  db:
    image: postgres:latest
    container_name: benjamit_database
    environment:
      POSTGRES_DB: benjamit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - benjamit
      
    restart: always

networks:
  benjamit:
    external: true

volumes:
  pgdata: {}